#!/bin/sh

source ~/.config/sabs.conf
cd ~/.abs-pkg

abs_root() {
	$SABS_SUDO $@
}

log() {
	echo -e "\e[1;34m::\e[0m" $@
}

usage() {
	echo "Usage: sabs <build|ebd|ebb>"
}

gen_patch() {
	backup=$(mktemp -d ~/.cache/abs-pkg/abs.XXXXXX)

	touch $1
	patch < $1
	cp -R * $backup

	log "Opening shell..."

	export PS1="(sabs) $PS1"
	bash

	diff -r $backup . > "$1"
	log "Generating patch..."

	rm -rf $backup
}

case $1 in
	"build")
		log "Building $2..."
		cd ~/.abs-pkg/$2

		if [[ -z $1 ]]
		then
			echo "Usage: sabs build <package>"
		fi

		mkdir .sabs &> /dev/null
		gen_patch .sabs/preinstall.patch

		makepkg -os
		;;
	*)
		usage
		;;
esac
