#!/bin/sh

AUR="https://aur.archlinux.org"

search() {
	url="$AUR/rpc/?type=search&by=name-desc&arg=$1"

	# jq -r '.results[] | (" " + .Name, .Description)'
	curl -s "$url" | jq -rcM\
		'.results[] | ("[1;33m" + .Name +
			" [32m" + .Version + "[0m",
		"    " + .Description)'
}

install() {
}

while getopts ":s:" arg
do
	case "$arg" in
		"s")
			search "$OPTARG"
			;;
		"i")
			install "$OPTARG"
			;;
		":")
			echo "-${OPTARG} expects an argument"
			;;
		"?")
			echo "Invalid option -${OPTARG}"
			;;
	esac
done
