#!/bin/sh

log() {
	echo -e "\e[1;34m::\e[0m" $@
}

usage() {
	echo "Usage: sabs-git <url>" 1>&2
	exit 255
}

[[ -z $1 ]] && usage

pkgbuildpath="PKGBUILD"

while getopts ":hp:" opt
do
	case "$opt" in
		h)
			usage
			;;
		p)
			pkgbuildpath="$OPTARG"
			;;
		*)
			usage
			;;
	esac
done

shift $((OPTIND - 1))

dir=$(basename $1 .git)
log "Downloading from $1 to $dir"
mkdir ~/.local/abs-pkg/$dir &> /dev/null
cd ~/.local/abs-pkg/$dir

git clone $1 orig-src
touch predownload.patch
touch prebuild.patch

echo -e "#!/bin/sh
cd orig-src

git remote update
remote=\$(git rev-parse origin/HEAD)
current=\$(git rev-parse HEAD)

if [[ \"\$remote\" == \"\$current\" ]]
then
	exit 255
fi
echo -e '-- Updating $dir'
git pull origin
exit 0
" > update
chmod u+x update

echo "$pkgbuildpath" > pkgbuild.path
