#!/bin/sh

log() {
	echo -e "\e[1;34m::\e[0m" $@
}

usage() {
	echo "Usage: sabs-git <url>" 1>&2
}

dir=$(basename $1 .git)
log "Downloading from $1 to $dir"
mkdir ~/.abs-pkg/$dir &> /dev/null
cd ~/.abs-pkg/$dir

git clone $1 orig-src
touch predownload.patch
touch prebuild.patch

if [[ -z $2 ]]
then
	echo "PKGBUILD" > pkgbuild.path
else
	echo "$2" > pkgbuild.path
fi

echo -e "#!/bin/sh
cd orig-src

remote=\$(git rev-parse origin/HEAD)
current=\$(git rev-parse HEAD)

if [[ \"\$remote\" == \"\$current\" ]]
then
	exit 255
fi
echo -e '-- Updating $dir'
git pull origin
exit 0
" > update
chmod u+x update
