#!/bin/sh

AUR="https://aur.archlinux.org"

search() {
	url="$AUR/rpc/?type=search&by=name-desc&arg=$1"

	curl -s "$url" | jq -rcM\
		'.results[] | ("[1;33m" + .Name +
			" [32m" + .Version + "[0m",
		"    " + .Description)'
}

install() {
	cd ~/.local/abs-pkg
	mkdir "$1"
	cd "$1"

	git clone "https://aur.archlinux.org/$1.git" orig-src
	touch predownload.patch
	touch prebuild.patch

	echo -e "#!/bin/sh
	cd orig-src

	git remote update
	remote=\$(git rev-parse origin/HEAD)
	current=\$(git rev-parse HEAD)

	if [[ \"\$remote\" == \"\$current\" ]]
	then
		exit 255
	fi
	echo -e '-- Updating $1'
	git pull origin
	exit 0
	" > update
	chmod u+x update

	echo PKGBUILD > pkgbuild.path
}

while getopts ":s:i:" arg
do
	case "$arg" in
		"s")
			search "$OPTARG"
			;;
		"i")
			install "$OPTARG"
			;;
		":")
			echo "-${OPTARG} expects an argument"
			;;
		"?")
			echo "Invalid option -${OPTARG}"
			;;
	esac
done
